# shellcheck shell=bash
# Concourse orchestrator.
#
# render  writes generated/concourse/pipeline.yml and vars.yml.  Job "ci" runs
#         the ci stages on every push; job "cd" runs all stages and is started
#         by hand once ci passed.
# publish downloads fly from the server and sets the pipeline.
# run     triggers a job and watches it:  run [--phase ci|cd]

pipeline_name() { printf '%s' "$PROJECT_NAME"; }
concourse_url() { host_url "$(value CONCOURSE_HOST_PORT 8083)"; }
fly_target() { printf 'devops-%s' "$PROJECT_NAME"; }

module_secrets() {
  ask CONCOURSE_HOST_PORT "Concourse port on this machine" 8083
  ask CONCOURSE_USER "Concourse user" admin
  ask_secret CONCOURSE_PASSWORD "Concourse password" "$(random_password)"
  ask_secret CONCOURSE_DB_PASSWORD "Concourse database password" "$(random_password)"
  ask_secret CONCOURSE_CLIENT_SECRET "Concourse web client secret" "$(random_password)"
  ask_secret CONCOURSE_TSA_CLIENT_SECRET "Concourse TSA client secret" "$(random_password)"
  ask MAVEN_IMAGE "Docker image for build tasks" "maven:3.9-eclipse-temurin-17"
}

yaml_quote() { local v=${1//\'/\'\'}; printf "'%s'" "$v"; }

# render_job <ci|cd>: the ci job runs ci stages, the cd job runs all stages.
render_job() {
  local job=$1 flags phase name args key image
  flags="$(maven_flags "") -Dmaven.repo.local=../.m2/repository"
  image=$(value MAVEN_IMAGE maven:3.9-eclipse-temurin-17)

  printf '  - name: %s\n    plan:\n      - get: source\n' "$job"
  if [[ $job == ci ]]; then
    printf '        trigger: true\n'
  else
    printf '        passed: [ci]\n'
  fi
  printf '      - task: %s\n        config:\n          platform: linux\n' "$job"
  printf '          image_resource:\n            type: registry-image\n            source:\n'
  printf '              repository: %s\n              tag: %s\n' "${image%:*}" "$(yaml_quote "${image##*:}")"
  printf '          inputs:\n            - name: source\n'
  printf '          caches:\n            - path: .m2\n'
  printf '          params:\n'
  while IFS= read -r key; do
    printf '            %s: ((%s))\n' "$key" "$key"
  done < "$DEVOPS_ENV/pipeline.keys"
  printf '          run:\n            dir: source\n            path: sh\n            args:\n              - -ec\n              - |\n'
  printf '                command -v git > /dev/null || { apt-get update -qq && apt-get install -y -qq git openssh-client > /dev/null; }\n'
  printf '                %s\n' "$(pipeline_git_setup)"
  while IFS='|' read -r _ phase name args; do
    [[ $job == ci && $phase != ci ]] && continue
    printf '                echo "==> %s"\n                mvn %s %s\n' "$name" "$flags" "$args"
  done < <(pipeline_stages)
}

module_render() {
  local dir="$DEVOPS_GENERATED/concourse" line key
  mkdir -p "$dir"
  {
    printf '# Generated by mvn-devops. Re-create with: devops.sh render\n'
    printf 'resources:\n  - name: source\n    type: git\n    icon: github\n    source:\n'
    printf '      uri: https://github.com/((GITHUB_REPOSITORY)).git\n'
    printf '      branch: ((GIT_BRANCH))\n'
    printf '      username: ((GITHUB_USERNAME))\n'
    printf '      password: ((GITHUB_TOKEN))\n\n'
    printf 'jobs:\n'
    render_job ci
    render_job cd
  } > "$dir/pipeline.yml"

  ( umask 077
    while IFS= read -r line; do
      key=${line%%=*}
      printf '%s: %s\n' "$key" "$(yaml_quote "${line#*=}")"
    done < "$DEVOPS_ENV/pipeline.env" > "$dir/vars.yml"
  )
  log_ok "Wrote $dir/pipeline.yml"
  log_ok "Wrote $dir/vars.yml"
}

fly_bin() {
  local bin="$DEVOPS_STATE/bin/fly" platform arch
  case $(uname -s) in
    Linux*) platform=linux ;;
    Darwin*) platform=darwin ;;
    MINGW*|MSYS*|CYGWIN*) platform=windows; bin+=.exe ;;
    *) die "Unsupported platform $(uname -s)" ;;
  esac
  case $(uname -m) in
    x86_64|amd64) arch=amd64 ;;
    arm64|aarch64) arch=arm64 ;;
    *) die "Unsupported architecture $(uname -m)" ;;
  esac
  if [[ ! -x $bin ]]; then
    mkdir -p "$(dirname "$bin")"
    curl -sfL "$(concourse_url)/api/v1/cli?arch=$arch&platform=$platform" -o "$bin" \
      || die "Could not download fly from $(concourse_url)"
    chmod +x "$bin"
  fi
  printf '%s' "$bin"
}

fly() {
  "$(fly_bin)" --target "$(fly_target)" "$@"
}

module_configure() {
  wait_http "$(concourse_url)/api/v1/info" 300 '^200$' || die "Concourse did not start. Check '$DEVOPS_CMD logs concourse'."
  fly login --concourse-url "$(concourse_url)" --team-name main \
    --username "$(value CONCOURSE_USER admin)" --password "$(require_value CONCOURSE_PASSWORD)" > /dev/null
  log_ok "Logged in to Concourse"
}

module_publish() {
  local dir="$DEVOPS_GENERATED/concourse"
  fly set-pipeline --non-interactive --pipeline "$(pipeline_name)" \
    --config "$dir/pipeline.yml" --load-vars-from "$dir/vars.yml"
  fly unpause-pipeline --pipeline "$(pipeline_name)"
  log_ok "Pipeline '$(pipeline_name)' is set at $(concourse_url)/teams/main/pipelines/$(pipeline_name)"
}

module_run() {
  local job=ci
  while (( $# )); do
    case $1 in
      --phase) job=$2; shift 2 ;;
      *) die "run: unknown option $1 (use --phase ci|cd)" ;;
    esac
  done
  [[ $job == ci || $job == cd ]] || die "--phase must be ci or cd"
  fly status > /dev/null 2>&1 || module_configure
  fly trigger-job --job "$(pipeline_name)/$job" --watch
}

module_urls() {
  printf '  %-12s %s   (%s / devops.sh get CONCOURSE_PASSWORD)\n' Concourse "$(concourse_url)" "$(value CONCOURSE_USER admin)"
}
