# shellcheck shell=bash
# Project state: profile, value store and generated env files.
#
# Everything the framework remembers about a project lives in
# "$PROJECT_DIR/.devops" (git-ignored):
#
#   profile.conf        selected modules
#   values/<KEY>        one file per value (chmod 600); .secret lists masked keys
#   env/compose.env     every value, used by docker compose for ${VAR} substitution
#   env/pipeline.env    variables handed to the pipeline (KEY=VALUE)
#   env/pipeline.sh     the same variables as bash exports
#   env/pipeline.keys   names of the pipeline variables, one per line
#   generated/          rendered pipeline definitions (Jenkins, Concourse, ...)
#   keys/               generated SSH keys

state_init_paths() {
  DEVOPS_STATE="$PROJECT_DIR/.devops"
  DEVOPS_VALUES="$DEVOPS_STATE/values"
  DEVOPS_ENV="$DEVOPS_STATE/env"
  DEVOPS_GENERATED="$DEVOPS_STATE/generated"
  DEVOPS_KEYS="$DEVOPS_STATE/keys"
  DEVOPS_PROFILE="$DEVOPS_STATE/profile.conf"
  export DEVOPS_STATE DEVOPS_VALUES DEVOPS_ENV DEVOPS_GENERATED DEVOPS_KEYS DEVOPS_PROFILE
}

state_ensure_dirs() {
  mkdir -p "$DEVOPS_VALUES" "$DEVOPS_ENV" "$DEVOPS_GENERATED" "$DEVOPS_KEYS"
  chmod 700 "$DEVOPS_VALUES" "$DEVOPS_KEYS" 2>/dev/null || true
  [[ -f "$DEVOPS_STATE/.gitignore" ]] || printf '*\n' > "$DEVOPS_STATE/.gitignore"
}

# ---------------------------------------------------------------- profile

profile_exists() { [[ -f "$DEVOPS_PROFILE" ]]; }

profile_load() {
  profile_exists || die "No profile found in $DEVOPS_STATE. Run '$DEVOPS_CMD init' first."
  # shellcheck disable=SC1090
  source "$DEVOPS_PROFILE"
  : "${PROJECT_NAME:?profile is missing PROJECT_NAME}"
  : "${ORCHESTRATOR:?profile is missing ORCHESTRATOR}"
  : "${MODULES:?profile is missing MODULES}"
  export PROJECT_NAME ORCHESTRATOR MODULES
}

profile_save() {
  state_ensure_dirs
  {
    printf '# Generated by mvn-devops. Edit with "%s init".\n' "$DEVOPS_CMD"
    printf 'PROJECT_NAME=%q\n' "$PROJECT_NAME"
    printf 'ORCHESTRATOR=%q\n' "$ORCHESTRATOR"
    printf 'MODULES=%q\n' "$MODULES"
  } > "$DEVOPS_PROFILE"
}

# ---------------------------------------------------------------- values

has_value() { [[ -f "$DEVOPS_VALUES/$1" ]]; }

value() {
  local key=$1
  if [[ -f "$DEVOPS_VALUES/$key" ]]; then
    cat "$DEVOPS_VALUES/$key"
  else
    printf '%s' "${2:-}"
  fi
}

require_value() {
  has_value "$1" || die "Value '$1' is not set. Run '$DEVOPS_CMD secrets' first."
  value "$1"
}

is_secret() { grep -qx "$1" "$DEVOPS_VALUES/.secret" 2>/dev/null; }

set_value() {
  local key=$1 val=$2 secret=${3:-}
  [[ $key =~ ^[A-Z][A-Z0-9_]*$ ]] || die "Invalid value name '$key'"
  [[ $val != *$'\n'* ]] || die "Value '$key' must be a single line"
  state_ensure_dirs
  ( umask 077; printf '%s' "$val" > "$DEVOPS_VALUES/$key" )
  if [[ $secret == secret ]] && ! is_secret "$key"; then
    printf '%s\n' "$key" >> "$DEVOPS_VALUES/.secret"
  fi
}

mask() {
  local key=$1 val=$2
  if is_secret "$key" && [[ -n $val ]]; then
    printf '%s' '********'
  else
    printf '%s' "$val"
  fi
}

# ask KEY "Question" [default]
# Keeps an existing value unless DEVOPS_RECONFIGURE=1.
ask() {
  local key=$1 question=$2 default=${3:-} current answer
  if has_value "$key" && [[ ${DEVOPS_RECONFIGURE:-0} != 1 ]]; then
    log_dim "  $key = $(mask "$key" "$(value "$key")")"
    return
  fi
  current=$(value "$key" "$default")
  if [[ ${DEVOPS_DEFAULTS:-0} == 1 ]]; then
    answer=$current
  else
    read -r -p "  $question [$current]: " answer || true
    answer=${answer:-$current}
  fi
  set_value "$key" "$answer"
}

# ask_secret KEY "Question" [default]
# Input is hidden; an empty answer keeps the current value or the default.
ask_secret() {
  local key=$1 question=$2 default=${3:-} current answer shown
  if has_value "$key" && [[ ${DEVOPS_RECONFIGURE:-0} != 1 ]]; then
    set_value "$key" "$(value "$key")" secret
    log_dim "  $key = ********"
    return
  fi
  current=$(value "$key" "$default")
  if [[ ${DEVOPS_DEFAULTS:-0} == 1 ]]; then
    answer=$current
  else
    shown='empty'
    [[ -n $current ]] && shown='keep current'
    read -r -s -p "  $question [$shown]: " answer || true
    printf '\n'
    answer=${answer:-$current}
  fi
  set_value "$key" "$answer" secret
}

# A random password that satisfies the usual complexity rules.
random_password() {
  local raw
  raw=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom 2>/dev/null | head -c 16 || true)
  printf 'Dv-%sa1' "$raw"
}

# ---------------------------------------------------------------- env files

# Called from a module's module_env hook.
pipeline_var() {
  local key=$1 val=${2-}
  [[ -n ${PIPELINE_VARS_FILE:-} ]] || die "pipeline_var used outside module_env"
  [[ $val != *$'\n'* ]] || die "Pipeline variable '$key' must be a single line"
  printf '%s=%s\n' "$key" "$val" >> "$PIPELINE_VARS_FILE"
}

# Mark a pipeline variable as secret without storing it as a value.
pipeline_secret() {
  pipeline_var "$1" "${2-}"
  if ! is_secret "$1"; then
    state_ensure_dirs
    printf '%s\n' "$1" >> "$DEVOPS_VALUES/.secret"
  fi
}

# Regenerates env/*.  Values first, then pipeline variables from every module.
env_generate() {
  state_ensure_dirs
  local tmp key file
  tmp=$(mktemp)
  PIPELINE_VARS_FILE=$tmp
  export PIPELINE_VARS_FILE
  local id
  for id in $MODULES; do
    module_hook "$id" module_env
  done
  unset PIPELINE_VARS_FILE

  # Last definition wins, order of first appearance is kept.
  awk -F= '!seen[$1]++ { order[++n] = $1 } { val[$1] = substr($0, length($1) + 2) }
           END { for (i = 1; i <= n; i++) print order[i] "=" val[order[i]] }' "$tmp" > "$DEVOPS_ENV/pipeline.env"
  rm -f "$tmp"
  chmod 600 "$DEVOPS_ENV/pipeline.env"
  cut -d= -f1 "$DEVOPS_ENV/pipeline.env" > "$DEVOPS_ENV/pipeline.keys"

  ( umask 077
    {
      printf '# Generated by mvn-devops. Do not edit.\n'
      while IFS= read -r line; do
        key=${line%%=*}
        printf 'export %s=%q\n' "$key" "${line#*=}"
      done < "$DEVOPS_ENV/pipeline.env"
    } > "$DEVOPS_ENV/pipeline.sh"

    {
      printf 'DEVOPS_HOME=%s\n' "$DEVOPS_HOME"
      printf 'DEVOPS_STATE=%s\n' "$DEVOPS_STATE"
      printf 'PROJECT_DIR=%s\n' "$PROJECT_DIR"
      printf 'PROJECT_NAME=%s\n' "$PROJECT_NAME"
      for file in "$DEVOPS_VALUES"/*; do
        [[ -f $file ]] || continue
        printf '%s=%s\n' "$(basename "$file")" "$(cat "$file")"
      done
      cat "$DEVOPS_ENV/pipeline.env"
    } > "$DEVOPS_ENV/compose.env"
  )
}

env_show() {
  local line key
  [[ -f "$DEVOPS_ENV/pipeline.env" ]] || die "No env generated yet. Run '$DEVOPS_CMD env'."
  while IFS= read -r line; do
    key=${line%%=*}
    printf '%s=%s\n' "$key" "$(mask "$key" "${line#*=}")"
  done < "$DEVOPS_ENV/pipeline.env"
}

# ---------------------------------------------------------------- URLs

# Where does the pipeline run?  "host" (plain maven) or "docker" (Jenkins,
# Concourse).  Pipeline URLs must use container hostnames in the latter case.
pipeline_url() {
  local service=$1 internal_port=$2 host_port=$3 path=${4:-}
  if [[ ${DEVOPS_RUNS_IN:-host} == docker ]]; then
    printf 'http://%s:%s%s' "$service" "$internal_port" "$path"
  else
    printf 'http://localhost:%s%s' "$host_port" "$path"
  fi
}

# URL used by the framework itself, which always runs on the host.
host_url() { printf 'http://localhost:%s%s' "$1" "${2:-}"; }
