# shellcheck shell=bash
# Jenkins orchestrator.
#
# render  writes generated/jenkins/Jenkinsfile and casc.yaml.  casc.yaml creates
#         the admin user, one secret-text credential per secret pipeline
#         variable and a pipeline job whose script is the Jenkinsfile.
# publish recreates the Jenkins container so it reloads env and casc.yaml.
# run     triggers the job and streams its console.

job_name() { printf '%s' "$PROJECT_NAME"; }

module_secrets() {
  ask JENKINS_HOST_PORT "Jenkins port on this machine" 8080
  ask JENKINS_ADMIN_USER "Jenkins admin user" admin
  ask_secret JENKINS_ADMIN_PASSWORD "Jenkins admin password" "$(random_password)"
}

render_jenkinsfile() {
  local name args flags key
  flags=$(maven_flags "")
  printf 'pipeline {\n  agent any\n'
  printf '  options {\n    timestamps()\n    disableConcurrentBuilds()\n  }\n'
  printf '  environment {\n'
  while IFS= read -r key; do
    printf "    %s = credentials('%s')\n" "$key" "$key"
  done < <(pipeline_secret_keys)
  printf '  }\n  stages {\n'
  printf "    stage('checkout') {\n      steps {\n"
  printf "        git url: 'https://github.com/' + env.GITHUB_REPOSITORY + '.git', branch: env.GIT_BRANCH, credentialsId: 'github-https'\n"
  printf "        sh '%s'\n      }\n    }\n" "$(pipeline_git_setup)"
  while IFS='|' read -r _ _ name args; do
    printf "    stage('%s') {\n      steps {\n        sh 'mvn %s %s'\n      }\n    }\n" "$name" "$flags" "$args"
  done < <(pipeline_stages)
  printf '  }\n}\n'
}

render_casc() {
  local jenkinsfile=$1 key
  cat <<EOF
# Generated by mvn-devops. Re-create with: devops.sh render
jenkins:
  systemMessage: "mvn-devops pipeline for $PROJECT_NAME"
  numExecutors: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "\${JENKINS_ADMIN_USER}"
          password: "\${JENKINS_ADMIN_PASSWORD}"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
unclassified:
  location:
    url: "$(host_url "$(value JENKINS_HOST_PORT 8080)")/"
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-https"
              description: "GitHub user and token"
              username: "\${GITHUB_USERNAME}"
              password: "\${GITHUB_TOKEN}"
EOF
  while IFS= read -r key; do
    cat <<EOF
          - string:
              scope: GLOBAL
              id: "$key"
              secret: "\${$key:-}"
EOF
  done < <(pipeline_secret_keys)
  cat <<EOF
jobs:
  - script: |
      pipelineJob('$(job_name)') {
        description('Generated by mvn-devops')
        definition {
          cps {
            sandbox(true)
            script('''
EOF
  # casc substitutes \${VAR}; ^\${ keeps a literal \${ in the job script.
  sed -e 's/\${/^${/g' -e 's/^/              /' "$jenkinsfile"
  cat <<EOF
            ''')
          }
        }
      }
EOF
}

module_render() {
  local dir="$DEVOPS_GENERATED/jenkins"
  mkdir -p "$dir"
  render_jenkinsfile > "$DEVOPS_GENERATED/Jenkinsfile"
  render_casc "$DEVOPS_GENERATED/Jenkinsfile" > "$dir/casc.yaml"
  log_ok "Wrote $DEVOPS_GENERATED/Jenkinsfile"
  log_ok "Wrote $dir/casc.yaml"
}

# up: casc.yaml must exist before the container starts.
module_prepare() {
  module_render
}

jenkins_url() { host_url "$(value JENKINS_HOST_PORT 8080)"; }

# jenkins_api <method> <path> [curl args]: authenticated call with a crumb.
jenkins_api() {
  local method=$1 path=$2; shift 2
  local auth jar crumb
  auth="$(value JENKINS_ADMIN_USER admin):$(value JENKINS_ADMIN_PASSWORD)"
  jar=$(mktemp)
  crumb=$(curl -s -c "$jar" -u "$auth" "$(jenkins_url)/crumbIssuer/api/json" | jq -r '.crumbRequestField + ":" + .crumb' 2>/dev/null || true)
  curl -s -b "$jar" -u "$auth" -H "$crumb" -X "$method" "$(jenkins_url)$path" "$@"
  rm -f "$jar"
}

module_configure() {
  wait_http "$(jenkins_url)/login" 600 '^200$' || die "Jenkins did not start. Check '$DEVOPS_CMD logs jenkins'."
}

module_publish() {
  log_step "Jenkins: reload configuration"
  compose up -d --no-deps --force-recreate jenkins
  module_configure
  local status
  status=$(jenkins_api GET "/job/$(job_name)/api/json" -o /dev/null -w '%{http_code}')
  [[ $status == 200 ]] || die "Job '$(job_name)' was not created (HTTP $status). Check '$DEVOPS_CMD logs jenkins'."
  log_ok "Job '$(job_name)' is ready at $(jenkins_url)/job/$(job_name)/"
}

module_run() {
  local headers location number='' start=0 size more result
  headers=$(mktemp)
  jenkins_api POST "/job/$(job_name)/build" -D "$headers" -o /dev/null
  location=$(awk 'tolower($1) == "location:" { print $2 }' "$headers" | tr -d '\r')
  rm -f "$headers"
  [[ -n $location ]] || die "Jenkins did not accept the build request. Is it published? Run '$DEVOPS_CMD publish'."

  log_step "Jenkins: waiting for an executor"
  while [[ -z $number || $number == null ]]; do
    sleep 2
    number=$(jenkins_api GET "${location#"$(jenkins_url)"}api/json" | jq -r '.executable.number // empty')
  done
  log_info "Build #$number: $(jenkins_url)/job/$(job_name)/$number/console"

  headers=$(mktemp)
  while true; do
    jenkins_api GET "/job/$(job_name)/$number/logText/progressiveText?start=$start" -D "$headers"
    size=$(awk 'tolower($1) == "x-text-size:" { print $2 }' "$headers" | tr -d '\r')
    more=$(awk 'tolower($1) == "x-more-data:" { print $2 }' "$headers" | tr -d '\r')
    start=${size:-$start}
    [[ $more == true ]] || break
    sleep 2
  done
  rm -f "$headers"

  result=$(jenkins_api GET "/job/$(job_name)/$number/api/json" | jq -r '.result')
  [[ $result == SUCCESS ]] || die "Build #$number finished with $result"
  log_ok "Build #$number succeeded"
}

module_urls() {
  printf '  %-12s %s   (%s / devops.sh get JENKINS_ADMIN_PASSWORD)\n' Jenkins "$(jenkins_url)" "$(value JENKINS_ADMIN_USER admin)"
}
