# shellcheck shell=bash
# Local orchestrator: runs every stage with mvn on this machine.
# The tools still run in containers and are reached through localhost.

# Writes a standalone script, handy for IDE run configurations.
module_render() {
  local out="$DEVOPS_GENERATED/pipeline.sh" phase name args flags
  flags=$(maven_flags "$PROJECT_DIR")
  {
    printf '#!/usr/bin/env bash\n# Generated by mvn-devops. Re-create with: devops.sh render\nset -euo pipefail\n'
    printf 'source %q\n' "$DEVOPS_ENV/pipeline.sh"
    while IFS="|" read -r _ phase name args; do
      printf '\necho "==> [%s] %s"\nmvn %s %s\n' "$phase" "$name" "$flags" "$args"
    done < <(pipeline_stages)
  } > "$out"
  chmod 700 "$out"
  log_ok "Wrote $out"
}

module_run() {
  local dry=0 from="" only="" phase="" started=0 stage_phase name args flags line
  while (( $# )); do
    case $1 in
      --dry-run) dry=1; shift ;;
      --from) from=$2; shift 2 ;;
      --only) only=$2; shift 2 ;;
      --phase) phase=$2; shift 2 ;;
      *) die "run: unknown option $1 (use --dry-run, --from <stage>, --only <stage>, --phase ci|cd)" ;;
    esac
  done
  [[ -z $from ]] && started=1
  flags=$(maven_flags "$PROJECT_DIR")
  command -v mvn > /dev/null || (( dry )) || die "mvn is not installed"

  local -a stages=()
  mapfile -t stages < <(pipeline_stages)
  for line in "${stages[@]}"; do
    IFS="|" read -r _ stage_phase name args <<< "$line"
    [[ $name == "$from" ]] && started=1
    (( started )) || continue
    [[ -n $only && $name != "$only" ]] && continue
    [[ -n $phase && $stage_phase != "$phase" ]] && continue
    log_step "[$stage_phase] $name"
    log_dim "mvn $flags $args"
    (( dry )) && continue
    # shellcheck disable=SC1091
    ( source "$DEVOPS_ENV/pipeline.sh"; cd "$PROJECT_DIR"; eval "mvn $flags $args" ) \
      || die "Stage '$name' failed. Resume with '$DEVOPS_CMD run --from $name'."
  done
  (( started )) || die "No stage named '$from'. See '$DEVOPS_CMD stages'."
  log_ok "Pipeline finished"
}
